### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by mishailovic** [egg0001/telegram-e-hentaiDL-bot#1]
How about adding the upload function to the bot?  You send a link of the gallery, it sends you an archive with pictures.

**Comment by egg0001** [comment]
You mean the bot can do something like below:

1. Download a gallery from EH
2 Upload the downloaded images back to EH (in user's gallery)

Is this correct? I'm not familiar with My galleries in EH since I have never uploaded any images to EH.

**Comment by mishailovic** [comment]
@egg0001 You misunderstood me a little. I want a download implementation, as in this [bot](https://t.me/UptoTGbot).  The bot will just send you an archive with pictures. Only there is one problem, and this is a limitation of 50 MB per file for telegram api

**Comment by egg0001** [comment]
You mean after downloading and archiving the pictures, the bot will send you the archiving files. I will try to realize this function.

**Comment by mishailovic** [comment]
Exactly!  Thank you so much!

**Comment by egg0001** [comment]
I added the function you suggested before. It is a Linux only function, and the upload speed is low (~100 KB/S)

**Comment by mishailovic** [comment]
Perfectly. I will try the new version tomorrow. Thanks a lot. I am closing issue
